// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinanceLibrary.Data;

#nullable disable

namespace MyFinanceLibrary.Migrations
{
    [DbContext(typeof(MyFinanceContext))]
    [Migration("20230330072409_MigrationExpensesAsNegativeAdded")]
    partial class MigrationExpensesAsNegativeAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFinanceLibrary.Models.ExpenseType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Food"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Transport"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Housing"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Clothing"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Food"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Transport"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Housing"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Clothing"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MyFinanceLibrary.Models.FinancialOperation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeID")
                        .HasColumnType("int");

                    b.Property<int>("IncomeTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FinancialOperations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 10000m,
                            Balance = 10000m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3187),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 1000m,
                            Balance = 11000m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3230),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 2
                        },
                        new
                        {
                            ID = 3,
                            Amount = 100m,
                            Balance = 11100m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3233),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 3
                        },
                        new
                        {
                            ID = 4,
                            Amount = 10m,
                            Balance = 11110m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3236),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 4
                        },
                        new
                        {
                            ID = 5,
                            Amount = 1m,
                            Balance = 11111m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3239),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 5
                        },
                        new
                        {
                            ID = 6,
                            Amount = 10000m,
                            Balance = 21111m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3242),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 6
                        },
                        new
                        {
                            ID = 7,
                            Amount = 1000m,
                            Balance = 22111m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3248),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 7
                        },
                        new
                        {
                            ID = 8,
                            Amount = 100m,
                            Balance = 22211m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3251),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 8
                        },
                        new
                        {
                            ID = 9,
                            Amount = 10m,
                            Balance = 22221m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3253),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 9
                        },
                        new
                        {
                            ID = 10,
                            Amount = 1m,
                            Balance = 22222m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3256),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 10
                        },
                        new
                        {
                            ID = 11,
                            Amount = -1000m,
                            Balance = 21222m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3259),
                            ExpenseTypeID = 1,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 12,
                            Amount = -100m,
                            Balance = 21122m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3261),
                            ExpenseTypeID = 2,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 13,
                            Amount = -10m,
                            Balance = 21112m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3263),
                            ExpenseTypeID = 3,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 14,
                            Amount = -1m,
                            Balance = 21111m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3266),
                            ExpenseTypeID = 4,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 15,
                            Amount = -1000m,
                            Balance = 20111m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3268),
                            ExpenseTypeID = 5,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 16,
                            Amount = -100m,
                            Balance = 20011m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3271),
                            ExpenseTypeID = 6,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 17,
                            Amount = -10m,
                            Balance = 20001m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3273),
                            ExpenseTypeID = 7,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 18,
                            Amount = -1m,
                            Balance = 20000m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3275),
                            ExpenseTypeID = 8,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 19,
                            Amount = -1000m,
                            Balance = 19000m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3278),
                            ExpenseTypeID = 9,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 20,
                            Amount = -100m,
                            Balance = 18900m,
                            Date = new DateTime(2023, 3, 30, 10, 24, 9, 899, DateTimeKind.Local).AddTicks(3280),
                            ExpenseTypeID = 10,
                            IncomeTypeID = 0
                        });
                });

            modelBuilder.Entity("MyFinanceLibrary.Models.IncomeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Salary"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Gift"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Interest"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Bonus"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Salary"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Gift"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Interest"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Bonus"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
