// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinanceLibrary.Data;

#nullable disable

namespace MyFinanceLibrary.Migrations
{
    [DbContext(typeof(MyFinanceContext))]
    [Migration("20230330100602_MigrationBalanceDeleted")]
    partial class MigrationBalanceDeleted
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFinanceLibrary.Models.ExpenseType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Food"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Transport"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Housing"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Clothing"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MyFinanceLibrary.Models.FinancialOperation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpenseTypeID")
                        .HasColumnType("int");

                    b.Property<int>("IncomeTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("FinancialOperations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amount = 10000m,
                            Date = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 1
                        },
                        new
                        {
                            ID = 2,
                            Amount = 1000m,
                            Date = new DateTime(2023, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 2
                        },
                        new
                        {
                            ID = 3,
                            Amount = 100m,
                            Date = new DateTime(2023, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 3
                        },
                        new
                        {
                            ID = 4,
                            Amount = 10m,
                            Date = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 4
                        },
                        new
                        {
                            ID = 5,
                            Amount = 1m,
                            Date = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 5
                        },
                        new
                        {
                            ID = 6,
                            Amount = 10000m,
                            Date = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 1
                        },
                        new
                        {
                            ID = 7,
                            Amount = 1000m,
                            Date = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 2
                        },
                        new
                        {
                            ID = 8,
                            Amount = 100m,
                            Date = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 3
                        },
                        new
                        {
                            ID = 9,
                            Amount = 10m,
                            Date = new DateTime(2023, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 4
                        },
                        new
                        {
                            ID = 10,
                            Amount = 1m,
                            Date = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 0,
                            IncomeTypeID = 5
                        },
                        new
                        {
                            ID = 11,
                            Amount = -1000m,
                            Date = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 1,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 12,
                            Amount = -100m,
                            Date = new DateTime(2023, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 2,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 13,
                            Amount = -10m,
                            Date = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 3,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 14,
                            Amount = -1m,
                            Date = new DateTime(2023, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 4,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 15,
                            Amount = -1000m,
                            Date = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 5,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 16,
                            Amount = -100m,
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 1,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 17,
                            Amount = -10m,
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 2,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 18,
                            Amount = -1m,
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 3,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 19,
                            Amount = -1000m,
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 4,
                            IncomeTypeID = 0
                        },
                        new
                        {
                            ID = 20,
                            Amount = -100m,
                            Date = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpenseTypeID = 5,
                            IncomeTypeID = 0
                        });
                });

            modelBuilder.Entity("MyFinanceLibrary.Models.IncomeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Salary"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Gift"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Interest"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Bonus"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
