// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinanceLibrary.Data;

#nullable disable

namespace MyFinanceLibrary.Migrations
{
    [DbContext(typeof(MyFinanceContext))]
    [Migration("20230329110001_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyFinanceLibrary.Models.ExpenseType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("ExpenseTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Food",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Transport",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 3,
                            Name = "Housing",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 4,
                            Name = "Clothing",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Food",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 7,
                            Name = "Transport",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 8,
                            Name = "Housing",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 9,
                            Name = "Clothing",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 10,
                            Name = "Other",
                            Value = 100.0
                        });
                });

            modelBuilder.Entity("MyFinanceLibrary.Models.IncomeType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("IncomeTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Salary",
                            Value = 1000.0
                        },
                        new
                        {
                            ID = 2,
                            Name = "Gift",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 3,
                            Name = "Interest",
                            Value = 10.0
                        },
                        new
                        {
                            ID = 4,
                            Name = "Bonus",
                            Value = 500.0
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other",
                            Value = 0.0
                        },
                        new
                        {
                            ID = 6,
                            Name = "Salary",
                            Value = 1000.0
                        },
                        new
                        {
                            ID = 7,
                            Name = "Gift",
                            Value = 100.0
                        },
                        new
                        {
                            ID = 8,
                            Name = "Interest",
                            Value = 10.0
                        },
                        new
                        {
                            ID = 9,
                            Name = "Bonus",
                            Value = 500.0
                        },
                        new
                        {
                            ID = 10,
                            Name = "Other",
                            Value = 0.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
